# Generated by Django 5.1 on 2026-03-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garage_number', models.CharField(help_text='Уникальный номер ТС в учете цеха', max_length=20, unique=True, verbose_name='Гаражный номер')),
                ('vin', models.CharField(help_text='17-символьный идентификационный номер кузова', max_length=17, verbose_name='VIN номер')),
                ('brand_model', models.CharField(help_text='Например: ГАЗ 3309, КАМАЗ 5320 и т.д.', max_length=255, verbose_name='Марка и модель')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Фотография ТС')),
                ('pts_type', models.CharField(choices=[('pts', 'ПТС (бумажный паспорт)'), ('epts', 'ЭПТС (электронный паспорт)')], default='pts', max_length=10, verbose_name='Тип паспорта')),
                ('pts_series', models.CharField(blank=True, help_text='Например: 78 РС', max_length=4, verbose_name='Серия ПТС')),
                ('pts_number', models.CharField(blank=True, help_text='6 цифр', max_length=6, verbose_name='Номер ПТС')),
                ('pts_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ПТС')),
                ('pts_scan', models.FileField(blank=True, null=True, upload_to='vehicles/pts/', verbose_name='Скан ПТС')),
                ('epts_number', models.CharField(blank=True, help_text='Номер электронного паспорта', max_length=20, verbose_name='Номер ЭПТС')),
                ('epts_date', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ЭПТС')),
                ('epts_scan', models.FileField(blank=True, null=True, upload_to='vehicles/epts/', verbose_name='Скан ЭПТС')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['garage_number'],
            },
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
