# Generated by Django 5.1 on 2026-03-02 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_vehicle_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип кузова (детальный)')),
            ],
            options={
                'verbose_name': 'Тип кузова (детальный)',
                'verbose_name_plural': 'Типы кузова (детальные)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Марка и модель')),
            ],
            options={
                'verbose_name': 'Марка и модель',
                'verbose_name_plural': 'Марки и модели',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Категория ТС')),
            ],
            options={
                'verbose_name': 'Категория ТС',
                'verbose_name_plural': 'Категории ТС',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Цвет')),
            ],
            options={
                'verbose_name': 'Цвет кузова',
                'verbose_name_plural': 'Цвета кузова',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FuelType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип топлива')),
            ],
            options={
                'verbose_name': 'Тип топлива',
                'verbose_name_plural': 'Типы топлива',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Тип кузова')),
            ],
            options={
                'verbose_name': 'Тип кузова',
                'verbose_name_plural': 'Типы кузова',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.bodytype', verbose_name='Тип кузова (детальный)'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='brand_model',
            field=models.ForeignKey(blank=True, help_text='Выберите из справочника или создайте новую', null=True, on_delete=django.db.models.deletion.PROTECT, to='cards.brandmodel', verbose_name='Марка и модель'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.category', verbose_name='Категория ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.color', verbose_name='Цвет кузова'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.fueltype', verbose_name='Тип топлива'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cards.vehicletype', verbose_name='Тип кузова'),
        ),
    ]
