# Generated by Django 5.1 on 2026-03-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_bodytype_brandmodel_category_color_fueltype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='axles_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество осей'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='diagnostic_card_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата диагностической карты'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='diagnostic_card_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения диагностической карты'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='diagnostic_card_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер диагностической карты'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='diagnostic_card_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/diagnostic/', verbose_name='Скан диагностической карты'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_power_hp',
            field=models.IntegerField(blank=True, null=True, verbose_name='Мощность двигателя (л.с.)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Объём двигателя (л)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата установки ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_present',
            field=models.BooleanField(default=False, verbose_name='Наличие ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_type',
            field=models.CharField(blank=True, help_text='Например: ГБО-4, СНГ и т.д.', max_length=50, verbose_name='Тип ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Объём ГБО (л)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='grz_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ГРЗ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='grz_number',
            field=models.CharField(blank=True, help_text='Например: АА123БВ', max_length=6, verbose_name='Номер ГРЗ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='grz_series',
            field=models.CharField(blank=True, help_text='Например: 78', max_length=2, verbose_name='Серия ГРЗ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения страховки'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mass_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Масса (кг)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_km',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пробег (км)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='osago_date_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения ОСАГО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='osago_date_issued',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи ОСАГО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='osago_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер полиса ОСАГО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='osago_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/osago/', verbose_name='Скан полиса ОСАГО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_certificate_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата выдачи свидетельства'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_certificate_number',
            field=models.CharField(blank=True, max_length=6, verbose_name='Номер свидетельства регистрации'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_certificate_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/registration/', verbose_name='Скан свидетельства регистрации'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='reg_certificate_series',
            field=models.CharField(blank=True, max_length=4, verbose_name='Серия свидетельства регистрации'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tech_inspection_expiry',
            field=models.DateField(blank=True, null=True, verbose_name='Дата истечения техосмотра'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='to2_period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период ТО-2 (дней)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='to3_period_days',
            field=models.IntegerField(blank=True, null=True, verbose_name='Период ТО-3 (дней)'),
        ),
    ]
