# Generated by Django 5.1 on 2026-03-02 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fio', models.CharField(db_index=True, max_length=255, verbose_name='ФИО пользователя')),
                ('username', models.CharField(db_index=True, max_length=150, verbose_name='Логин пользователя')),
                ('action', models.CharField(choices=[('CREATE', 'Создание'), ('UPDATE', 'Изменение'), ('DELETE', 'Удаление'), ('VIEW', 'Просмотр')], db_index=True, max_length=20, verbose_name='Действие')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='Модель')),
                ('object_id', models.IntegerField(db_index=True, verbose_name='ID объекта')),
                ('object_description', models.CharField(max_length=500, verbose_name='Описание объекта')),
                ('changes', models.TextField(blank=True, help_text='Описание полей которые были изменены', verbose_name='Внесённые изменения')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата и время')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP адрес')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Записи аудита',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='cards_audit_timesta_5b0ee1_idx'), models.Index(fields=['user_fio', '-timestamp'], name='cards_audit_user_fi_3d8679_idx'), models.Index(fields=['action', '-timestamp'], name='cards_audit_action_a9c417_idx')],
            },
        ),
    ]
