# Generated by Django 5.1 on 2026-03-02 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата архивирования'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Архивировано пользователем'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, help_text='Снято с учета / выведено из эксплуатации', verbose_name='Архивировано'),
        ),
    ]
