# Generated by Django 5.1 on 2026-03-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_vehicle_archived_at_vehicle_archived_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='body_number',
            field=models.CharField(blank=True, help_text='20+ символов', max_length=50, verbose_name='Номер кузова'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bucket_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Ёмкость ковша (м³)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='bus_length',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Габаритная длина автобуса (м)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='cargo_capacity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Грузоподъемность (кг)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, help_text='20+ символов', max_length=50, verbose_name='Номер шасси'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='direction',
            field=models.CharField(blank=True, help_text='Дублирует первую цифру гаражного номера', max_length=1, verbose_name='Направление ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dismission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата снятия с учета в ГИБДД'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dprg_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата осмотра в ГИБДД (ДПОГ)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dprg_inspection_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/dprg/', verbose_name='Скан ДПОГ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='dprg_next_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего осмотра в ГИБДД (ДПОГ)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='empty_mass',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Масса без нагрузки (кг)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_model_number',
            field=models.CharField(blank=True, help_text='15+ символов', max_length=50, verbose_name='Модель, № двигателя'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='engine_power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Мощность двигателя (кВт)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_per_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расходы ГСМ (литр/час)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_summer_city',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расходы ГСМ (Лето город)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_summer_highway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расходы ГСМ (Лето трасса)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_type',
            field=models.CharField(blank=True, choices=[('liters_100km', 'литр / 100 км'), ('liters_hour', 'литр / час'), ('cubic_100km', 'м³ / 100 км'), ('hybrid', 'гибрид'), ('other', 'прочее')], max_length=20, verbose_name='Расходы ГСМ (тип единицы)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_winter_city',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расходы ГСМ (Зима город)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_consumption_winter_highway',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Расходы ГСМ (Зима трасса)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_grade',
            field=models.CharField(blank=True, help_text='ДТ, АИ-92, АИ-95, ГАЗ, Электро и комбинации', max_length=50, verbose_name='Марка ГСМ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_tank_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Ёмкость топливного бака (л)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_cylinders_count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество баллонов ГБО (шт.)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата освидетельствования ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_inspection_scan',
            field=models.FileField(blank=True, null=True, upload_to='vehicles/gbo/', verbose_name='Скан свидетельства ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_next_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующего освидетельствования ГБО'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='gbo_total_capacity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Общая ёмкость баллонов ГБО (л)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_lifting_equipment',
            field=models.BooleanField(default=False, verbose_name='Наличие подъемного оборудования'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_ssmt',
            field=models.BooleanField(default=False, verbose_name='Наличие ССМТ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='has_tachograph',
            field=models.BooleanField(default=False, verbose_name='Наличие тахографа'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='initial_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='10+ символов', max_digits=15, null=True, verbose_name='Первоначальная стоимость'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='inventory_number',
            field=models.CharField(blank=True, help_text='7+ символов', max_length=20, verbose_name='Инвентарный номер ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='mileage_type',
            field=models.CharField(blank=True, choices=[('km', 'Пробег для ТС (км)'), ('hours', 'Моточасы для ДСМ (час.)')], default='km', max_length=10, verbose_name='Тип пробега'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motor_hours',
            field=models.IntegerField(blank=True, null=True, verbose_name='Моточасы для ДСМ (час.)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='motorpool',
            field=models.CharField(blank=True, help_text='01, 02, 03 и т.д.', max_length=10, verbose_name='Автоколонна'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='osago_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Стоимость полиса ОСАГО (Р)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='passenger_capacity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Пассажировместимость (чел.)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tachograph_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата калибровки тахографа'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tachograph_next_calibration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата следующей калибровки тахографа'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='to2_periodicity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Периодичность проведения ТО-2 (км)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='ts_status',
            field=models.CharField(blank=True, help_text='в рейсе, ремонт, ТО-1, ТО-2, дежурство, простой', max_length=50, verbose_name='Статус ТС'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_for_military',
            field=models.CharField(blank=True, choices=[('passenger', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('flat_bed', 'Бортовой'), ('dump', 'Самосвал'), ('other', 'Прочее')], max_length=20, verbose_name='Тип ТС (для военкомата)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='vehicle_type_for_tax',
            field=models.CharField(blank=True, choices=[('passenger', 'Легковой'), ('truck', 'Грузовой'), ('bus', 'Автобус'), ('flat_bed', 'Бортовой'), ('dump', 'Самосвал'), ('other', 'Прочее')], max_length=20, verbose_name='Тип ТС (для налоговой)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='year_of_manufacture',
            field=models.CharField(blank=True, help_text='ГГГГ', max_length=4, verbose_name='Год изготовления'),
        ),
    ]
