# Generated by Django 5.1 on 2026-03-02 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_vehicle_body_number_vehicle_bucket_capacity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='accumulated_depreciation',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Накопленная амортизация (Р)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='date_in_service',
            field=models.DateField(blank=True, help_text='Для расчета износа и амортизации', null=True, verbose_name='Дата ввода в эксплуатацию'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depreciation_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Годовой процент амортизации', max_digits=5, null=True, verbose_name='Норма амортизации (%)'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='okof_code',
            field=models.CharField(blank=True, help_text='Общероссийский классификатор основных фондов (например: 1700000000194)', max_length=20, verbose_name='Код ОКОФ'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='residual_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Остаточная стоимость (Р)'),
        ),
    ]
