# Generated by Django 5.1 on 2026-03-02 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_vehicle_accumulated_depreciation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Дата последней ТО-2')),
                ('last_maintenance_mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег при последней ТО-2 (км)')),
                ('next_maintenance_date', models.DateField(db_index=True, verbose_name='Дата следующей ТО-2')),
                ('next_maintenance_mileage', models.IntegerField(blank=True, null=True, verbose_name='Пробег для следующей ТО-2 (км)')),
                ('status', models.CharField(choices=[('scheduled', 'Запланировано'), ('in_progress', 'В процессе'), ('completed', 'Завершено'), ('overdue', 'Просрочено'), ('cancelled', 'Отменено')], db_index=True, default='scheduled', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, help_text='Результаты ТО-2 или замечания', verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_schedules', to='cards.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Расписание ТО-2',
                'verbose_name_plural': 'Расписания ТО-2',
                'ordering': ['next_maintenance_date'],
                'indexes': [models.Index(fields=['vehicle', '-next_maintenance_date'], name='cards_maint_vehicle_b8c903_idx'), models.Index(fields=['status', 'next_maintenance_date'], name='cards_maint_status_c80dd6_idx')],
            },
        ),
    ]
