# Generated by Django 5.1 on 2026-03-07 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_maintenanceschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='ts_status',
            field=models.CharField(blank=True, choices=[('ready', 'Готово к эксплуатации'), ('in_operation', 'В рейсе'), ('maintenance_1', 'ТО-1'), ('maintenance_2', 'ТО-2'), ('repair', 'Ремонт'), ('inspection', 'Техосмотр'), ('standby', 'Дежурство'), ('idle', 'Простой'), ('archived', 'На консервации/Архив')], default='ready', help_text='Текущий статус транспортного средства', max_length=50, verbose_name='Статус ТС'),
        ),
    ]
